FROM golang:latest
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app ./cmd/app

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app .
CMD ["./app"]
