// CODE GENERATED BY goframe; DO NOT EDIT.
package db

import (
	embed "embed"

	"github.com/alexisvisco/goframe/db/migrate"
)

//go:embed migrations/*.sql
var fs embed.FS

// Migrations is a slice of migration.Migration
var Migrations = []migrate.Migration{
	migrate.MigrationFromSQL(fs, "migrations/20250526094143_new.sql"),
}
