name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-docs.yml
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Setup GitHub Pages
        id: setup_pages
        uses: actions/configure-pages@v5

      - name: Dump environment variables
        run: printenv

      - name: Show working directory & file tree
        run: |
          echo "== PWD =="
          pwd
          echo "== LS -la =="
          ls -la
          echo "== FILES IN DOCS =="
          find . -type f

      - name: Show next.config.js
        run: cat next.config.js || echo "no next.config.js"

      - name: Patch Next.js to log build failure
        run: |
          if [ -f node_modules/next/dist/build/index.js ]; then
            sed -i 's/process.exit(1)/console.error("❌ Forced exit from build"); process.exit(1)/g' node_modules/next/dist/build/index.js
          fi

      - name: Build with Next.js (full debug)
        run: |
          echo "== START BUILD =="
          echo "Using basePath: ${{ steps.setup_pages.outputs.base_path }}"
          NEXT_DEBUG=1 PAGES_BASE_PATH="${{ steps.setup_pages.outputs.base_path }}" npx next build --no-lint --no-types || (echo '❌ next build failed' && exit 1)
          echo "== END BUILD =="
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Dump .next folder
        run: |
          echo "== .next folder =="
          ls -R .next || echo "no .next directory"

      - name: Export static site
        run: |
          NEXT_DEBUG=1 PAGES_BASE_PATH="${{ steps.setup_pages.outputs.base_path }}" npx next export --debug || (echo '❌ next export failed' && exit 1)
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Run Pagefind (non-blocking)
        run: |
          npx pagefind --site out --output-path out/_pagefind || echo "⚠️ Pagefind failed (non-blocking)"

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
